// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSafeStorage } from '@/lib/safe-storage';

const SUPABASE_URL = "https://hkndhnctlctvybfftyqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrbmRobmN0bGN0dnliZmZ0eXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDI4OTEsImV4cCI6MjA3MDgxODg5MX0.G9DMDu3jiSiCR4eMMgJdpim778OQ0vNgiLlo_ViA2CA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const storage = getSafeStorage() ?? undefined;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
